// lib/mockData.ts - Updated to work with both your types and API types
import { AttendanceStats, CalendarEvent, Class, Student } from "@/types";
import type {
    Classroom,
    DashboardStats,
    TextbookEntry,
    User,
} from "@/types/api";

// Keep your existing mock data for backward compatibility
export const mockClasses: Class[] = [
    {
        id: "1",
        slug: "",
        name: "Classe de 6ème",
        level: "6ème",
        totalStudents: 65,
        boysCount: 40,
        girlsCount: 25,
        absentCount: 5,
        createdAt: "2024-09-01",
    },
    {
        id: "2",
        slug: "",
        name: "Classe de 5ème",
        level: "5ème",
        totalStudents: 50,
        boysCount: 30,
        girlsCount: 20,
        absentCount: 3,
        createdAt: "2024-09-01",
    },
    {
        id: "3",
        slug: "",
        name: "Classe de 4ème",
        level: "4ème",
        totalStudents: 70,
        boysCount: 45,
        girlsCount: 25,
        absentCount: 2,
        createdAt: "2024-09-01",
    },
];

export const mockStudents: Student[] = [
    {
        id: "1",
        slug: "",
        firstName: "Jerome",
        lastName: "Bell",
        classId: "1",
        className: "Classe de 6ème",
        isPresent: true,
        avatar: "/avatars/jerome.jpg",
    },
    {
        id: "2",
        slug: "",
        firstName: "Albert",
        lastName: "Flores",
        classId: "1",
        className: "Classe de 6ème",
        isPresent: true,
        avatar: "/avatars/albert.jpg",
    },
    {
        id: "3",
        slug: "",
        firstName: "Arlene",
        lastName: "McCoy",
        classId: "2",
        className: "Classe de 5ème",
        isPresent: false,
        avatar: "/avatars/arlene.jpg",
    },
    {
        id: "4",
        slug: "",
        firstName: "Jenny",
        lastName: "Wilson",
        classId: "2",
        className: "Classe de 5ème",
        isPresent: true,
        avatar: "/avatars/jenny.jpg",
    },
    {
        id: "5",
        slug: "",
        firstName: "Ralph",
        lastName: "Edwards",
        classId: "3",
        className: "Classe de 4ème",
        isPresent: true,
        avatar: "/avatars/ralph.jpg",
    },
    {
        id: "6",
        slug: "",
        firstName: "Darrell",
        lastName: "Steward",
        classId: "1",
        className: "Classe de 6ème",
        isPresent: true,
        avatar: "/avatars/darrell.jpg",
    },
    {
        id: "7",
        slug: "",
        firstName: "Kathryn",
        lastName: "Murphy",
        classId: "2",
        className: "Classe de 5ème",
        isPresent: true,
        avatar: "/avatars/kathryn.jpg",
    },
    {
        id: "8",
        slug: "",
        firstName: "Floyd",
        lastName: "Miles",
        classId: "3",
        className: "Classe de 4ème",
        isPresent: false,
        avatar: "/avatars/floyd.jpg",
    },
];

export const mockEvents: CalendarEvent[] = [
    {
        id: "1",
        slug: "",
        title: "Utilisation des nombres rationnels",
        type: "class",
        classId: "2",
        className: "Classe: 5ème",
        time: "10:30",
        date: "2024-12-31",
        color: "green",
    },
    {
        id: "2",
        slug: "",
        title: "Interrogation",
        type: "exam",
        classId: "1",
        className: "Classe: 6ème",
        time: "11:00",
        date: "2024-12-31",
        color: "purple",
    },
    {
        id: "3",
        slug: "",
        title: "Devoir",
        type: "homework",
        classId: "2",
        className: "Classe: 5ème",
        time: "14:00",
        date: "2024-12-31",
        color: "yellow",
    },
    {
        id: "4",
        slug: "",
        title: "Interrogation",
        type: "exam",
        classId: "2",
        className: "Classe: 5ème",
        time: "14:45",
        date: "2024-12-31",
        color: "purple",
    },
    {
        id: "5",
        slug: "",
        title: "Devoirs surveillés",
        type: "homework",
        classId: "2",
        className: "Classe: 5ème",
        time: "15:30",
        date: "2024-12-31",
        color: "yellow",
    },
    {
        id: "6",
        slug: "",
        title: "Contrôles surprise",
        type: "exam",
        classId: "1",
        className: "Classe: 6ème",
        time: "16:30",
        date: "2024-12-31",
        color: "green",
    },
];

export const mockAttendanceStats: AttendanceStats[] = [
    { month: "Jan", absents: 5 },
    { month: "Fév", absents: 12 },
    { month: "Mar", absents: 25 },
    { month: "Avr", absents: 30 },
    { month: "Mai", absents: 65 },
    { month: "Juin", absents: 32 },
    { month: "Juil", absents: 28 },
    { month: "Août", absents: 35 },
    { month: "Sep", absents: 42 },
    { month: "Oct", absents: 8 },
    { month: "Nov", absents: 15 },
    { month: "Déc", absents: 2 },
];

export const mockTextbookEntries: TextbookEntry[] = [
    {
        id: 1,
        slug: "",
        title: "Les nombres relatifs",
        description:
            "Lorem ipsum dolor sit amet consectetur. Turpis eleifend auctor........",
        subject: "Les nombres relatifs en détail et leur utilisation",
        content: `<div>
      <h3>Cours:</h3>
      <ul>
        <li>Rappel : Qu'est-ce qu'un nombre relatif ? (nombres entiers positifs, négatifs et zéro)</li>
        <li>Représentation sur une droite graduée : Placer des nombres relatifs, comparer des nombres relatifs.</li>
        <li>Opposé d'un nombre : Définition et exemples.</li>
        <li>Valeur absolue d'un nombre : Définition et interprétation géométrique.</li>
        <li>Utilisation des nombres relatifs dans la vie quotidienne : Température, altitude, etc.</li>
      </ul>
      
      <h3>Exercices:</h3>
      <ol>
        <li>Placez les nombres suivants sur une droite graduée : -3 ; 5 ; -1 ; 2 ; 0.</li>
        <li>Donnez l'opposé de : 7 ; -4 ; 0.</li>
        <li>Quelle est la valeur absolue de : -8 ; 3 ; -2 ?</li>
        <li>La température à Paris est de -2°C le matin et de 8°C l'après-midi. Quelle est la différence de température entre le matin et l'après-midi ?</li>
      </ol>
    </div>`,
        sessionDate: "20/12/2024",
        sessionTime: "10:30",
        nextSession: "23/12/2024",
        nextSessionTime: "10:30",
        submissionDate: "20/12/2024",
        isSubmitted: true,
        isOfflineCreated: false,
        principalStatus: "pending",
        inspectorStatus: "pending",
        school: "Lycée Moderne Andokoi",
        principalTeacher: "Mr Robert",
        classroom: "6 ème 1A",
        class: {
            id: 1,
            slug: "6eme-1a",
            name: "6 ème 1A",
            level: "6ème",
            academicYear: "2024-2025",
            isActive: true,
            createdAt: "2024-09-01T00:00:00Z",
            updatedAt: "2024-09-01T00:00:00Z",
        },
        teacher: {
            id: 1,
            slug: "stan-robert",
            firstName: "Stan",
            lastName: "Robert",
            fullName: "Stan Robert",
            email: "stan.robert@school.com",
        },
        createdAt: "2024-12-20T10:30:00Z",
        updatedAt: "2024-12-20T10:30:00Z",
    },
    {
        id: 2,
        slug: "",
        title: "Cahier de texte 2",
        description:
            "Lorem ipsum dolor sit amet consectetur. Turpis eleifend auctor........",
        subject: "Mathématiques - Géométrie",
        content: "<p>Contenu du cours de géométrie...</p>",
        sessionDate: "21/12/2024",
        sessionTime: "10:30",
        nextSession: "24/12/2024",
        nextSessionTime: "10:30",
        submissionDate: "21/12/2024",
        isSubmitted: true,
        isOfflineCreated: false,
        principalStatus: "pending",
        inspectorStatus: "pending",
        school: "Lycée Moderne Andokoi",
        principalTeacher: "Mr Robert",
        classroom: "6 ème 1A",
        class: {
            id: 1,
            slug: "6eme-1a",
            name: "6 ème 1A",
            level: "6ème",
            academicYear: "2024-2025",
            isActive: true,
            createdAt: "2024-09-01T00:00:00Z",
            updatedAt: "2024-09-01T00:00:00Z",
        },
        teacher: {
            id: 1,
            slug: "stan-robert",
            firstName: "Stan",
            lastName: "Robert",
            fullName: "Stan Robert",
            email: "stan.robert@school.com",
        },
        createdAt: "2024-12-21T10:30:00Z",
        updatedAt: "2024-12-21T10:30:00Z",
    },
    {
        id: 3,
        slug: "",
        title: "Cahier de texte 3",
        description:
            "Lorem ipsum dolor sit amet consectetur. Turpis eleifend auctor........",
        subject: "Français - Conjugaison",
        content: "<p>Contenu du cours de français...</p>",
        sessionDate: "22/12/2024",
        sessionTime: "14:30",
        nextSession: "25/12/2024",
        nextSessionTime: "14:30",
        submissionDate: "22/12/2024",
        isSubmitted: true,
        isOfflineCreated: false,
        principalStatus: "pending",
        inspectorStatus: "pending",
        school: "Lycée Moderne Andokoi",
        principalTeacher: "Mr Robert",
        classroom: "5 ème",
        class: {
            id: 2,
            slug: "5eme",
            name: "5 ème",
            level: "5ème",
            academicYear: "2024-2025",
            isActive: true,
            createdAt: "2024-09-01T00:00:00Z",
            updatedAt: "2024-09-01T00:00:00Z",
        },
        teacher: {
            id: 1,
            slug: "stan-robert",
            firstName: "Stan",
            lastName: "Robert",
            fullName: "Stan Robert",
            email: "stan.robert@school.com",
        },
        createdAt: "2024-12-22T14:30:00Z",
        updatedAt: "2024-12-22T14:30:00Z",
    },
];

// Helper functions to get data
export const getClassById = (id: string): Class | undefined => {
    return mockClasses.find(c => c.id === id);
};

export const getStudentsByClassId = (classId: string): Student[] => {
    return mockStudents.filter(s => s.classId === classId);
};

export const getTextbookEntriesByClassId = (
    classId: string
): TextbookEntry[] => {
    // Ensure both sides are compared as strings to avoid type mismatch
    return mockTextbookEntries.filter(
        t => t.class !== undefined && String(t.class.id) === String(classId)
    );
};

export const getTextbookEntryById = (id: string): TextbookEntry | undefined => {
    // Ensure both sides are compared as strings to avoid type mismatch
    return mockTextbookEntries.find(t => String(t.id) === String(id));
};

// Principal and Inspector Dashboard Mock Data
export const mockTeachers: User[] = [
    {
        id: 1,
        slug: "stan-robert",
        firstName: "Stan",
        lastName: "Robert",
        fullName: "Stan Robert",
        email: "stan.robert@school.com",
        role: "teacher",
        roleLabel: "Professeur",
        matricule: "T001",
        phone: "+225 0123456789",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Stan",
        isActive: true,
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
    },
    {
        id: 2,
        slug: "jane-cooper",
        firstName: "Jane",
        lastName: "Cooper",
        fullName: "Jane Cooper",
        email: "jane.cooper@school.com",
        role: "teacher",
        roleLabel: "Professeur",
        matricule: "T002",
        phone: "+225 0123456790",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane",
        isActive: true,
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
    },
    {
        id: 3,
        slug: "marvin-mckinney",
        firstName: "Marvin",
        lastName: "McKinney",
        fullName: "Marvin McKinney",
        email: "marvin.mckinney@school.com",
        role: "teacher",
        roleLabel: "Professeur",
        matricule: "T003",
        phone: "+225 0123456791",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Marvin",
        isActive: true,
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
    },
    {
        id: 4,
        slug: "courtney-henry",
        firstName: "Courtney",
        lastName: "Henry",
        fullName: "Courtney Henry",
        email: "courtney.henry@school.com",
        role: "teacher",
        roleLabel: "Professeur",
        matricule: "T004",
        phone: "+225 0123456792",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Courtney",
        isActive: true,
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
    },
];

export const mockClassroomsAPI: Classroom[] = [
    {
        id: 1,
        slug: "6eme-1a",
        name: "6ème 1A",
        level: "6ème",
        academicYear: "2024-2025",
        isActive: true,
        totalStudents: 75,
        studentsCount: 75,
        teacher: {
            id: 1,
            slug: "stan-robert",
            firstName: "Stan",
            lastName: "Robert",
            fullName: "Stan Robert",
            email: "stan.robert@school.com",
            avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Stan",
        },
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
    },
    {
        id: 2,
        slug: "6eme-1b",
        name: "6ème 1B",
        level: "6ème",
        academicYear: "2024-2025",
        isActive: true,
        totalStudents: 59,
        studentsCount: 59,
        teacher: {
            id: 2,
            slug: "jane-cooper",
            firstName: "Jane",
            lastName: "Cooper",
            fullName: "Jane Cooper",
            email: "jane.cooper@school.com",
            avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane",
        },
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
    },
    {
        id: 3,
        slug: "6eme-1c",
        name: "6ème 1C",
        level: "6ème",
        academicYear: "2024-2025",
        isActive: true,
        totalStudents: 60,
        studentsCount: 60,
        teacher: {
            id: 1,
            slug: "stan-robert",
            firstName: "Stan",
            lastName: "Robert",
            fullName: "Stan Robert",
            email: "stan.robert@school.com",
            avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Stan",
        },
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
    },
    {
        id: 4,
        slug: "5eme-a",
        name: "5ème A",
        level: "5ème",
        academicYear: "2024-2025",
        isActive: true,
        totalStudents: 55,
        studentsCount: 55,
        teacher: {
            id: 2,
            slug: "jane-cooper",
            firstName: "Jane",
            lastName: "Cooper",
            fullName: "Jane Cooper",
            email: "jane.cooper@school.com",
            avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane",
        },
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
    },
    {
        id: 5,
        slug: "5eme-b",
        name: "5ème B",
        level: "5ème",
        academicYear: "2024-2025",
        isActive: true,
        totalStudents: 45,
        studentsCount: 45,
        teacher: {
            id: 3,
            slug: "marvin-mckinney",
            firstName: "Marvin",
            lastName: "McKinney",
            fullName: "Marvin McKinney",
            email: "marvin.mckinney@school.com",
            avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Marvin",
        },
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
    },
    {
        id: 6,
        slug: "4eme-a",
        name: "4ème A",
        level: "4ème",
        academicYear: "2024-2025",
        isActive: true,
        totalStudents: 48,
        studentsCount: 48,
        teacher: {
            id: 4,
            slug: "courtney-henry",
            firstName: "Courtney",
            lastName: "Henry",
            fullName: "Courtney Henry",
            email: "courtney.henry@school.com",
            avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Courtney",
        },
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
    },
    {
        id: 7,
        slug: "4eme-b",
        name: "4ème B",
        level: "4ème",
        academicYear: "2024-2025",
        isActive: true,
        totalStudents: 40,
        studentsCount: 40,
        teacher: {
            id: 4,
            slug: "courtney-henry",
            firstName: "Courtney",
            lastName: "Henry",
            fullName: "Courtney Henry",
            email: "courtney.henry@school.com",
            avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Courtney",
        },
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
    },
    {
        id: 8,
        slug: "3eme-a",
        name: "3ème A",
        level: "3ème",
        academicYear: "2024-2025",
        isActive: true,
        totalStudents: 35,
        studentsCount: 35,
        teacher: {
            id: 4,
            slug: "courtney-henry",
            firstName: "Courtney",
            lastName: "Henry",
            fullName: "Courtney Henry",
            email: "courtney.henry@school.com",
            avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Courtney",
        },
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
    },
    {
        id: 9,
        slug: "3eme-b",
        name: "3ème B",
        level: "3ème",
        academicYear: "2024-2025",
        isActive: true,
        totalStudents: 50,
        studentsCount: 50,
        teacher: {
            id: 3,
            slug: "marvin-mckinney",
            firstName: "Marvin",
            lastName: "McKinney",
            fullName: "Marvin McKinney",
            email: "marvin.mckinney@school.com",
            avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Marvin",
        },
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
    },
];

export const mockPrincipalDashboardStats: DashboardStats = {
    totalClasses: 30,
    totalStudents: 2000,
    totalTeachers: 10,
    attendanceRate: 80,
    recentActivity: [
        {
            id: 1,
            type: "textbook_created",
            teacher: "Stan Robert",
            class: "6ème 1A",
            title: "Les nombres relatifs",
            timestamp: "2024-12-20T10:30:00Z",
        },
        {
            id: 2,
            type: "textbook_created",
            teacher: "Jane Cooper",
            class: "5ème",
            title: "Cahier de texte 5",
            timestamp: "2024-12-19T14:30:00Z",
        },
    ],
};

export const mockInspectorDashboardStats: DashboardStats = {
    totalClasses: 30,
    totalStudents: 2000,
    totalTeachers: 10,
    attendanceRate: 80,
    recentActivity: [
        {
            id: 1,
            type: "school_visit",
            school: "Collège Moderne Bessio",
            date: "2024-12-20",
            timestamp: "2024-12-20T09:00:00Z",
        },
        {
            id: 2,
            type: "textbook_reviewed",
            school: "Collège Moderne de Korhogo",
            teacher: "Prof. Martin",
            timestamp: "2024-12-19T15:30:00Z",
        },
    ],
};

export const mockSchools = [
    { name: "Collège Moderne Bessio", id: 1, slug: "college-moderne-bessio" },
    {
        name: "Collège Moderne de Korhogo",
        id: 2,
        slug: "college-moderne-de-korhogo",
    },
    { name: "Collège de Dabou", id: 3, slug: "college-de-dabou" },
    {
        name: "Collège moderne de cocody",
        id: 4,
        slug: "college-moderne-de-cocody",
    },
];

export const mockAbsenceData = [
    { month: "Jan", present: 5, absent: 2 },
    { month: "Fév", present: 12, absent: 5 },
    { month: "Mar", present: 25, absent: 8 },
    { month: "Avr", present: 30, absent: 10 },
    { month: "Mai", present: 65, absent: 10 },
    { month: "Juin", present: 32, absent: 8 },
    { month: "Juil", present: 28, absent: 5 },
    { month: "Août", present: 35, absent: 6 },
    { month: "Sep", present: 42, absent: 7 },
    { month: "Oct", present: 8, absent: 1 },
    { month: "Nov", present: 15, absent: 3 },
    { month: "Déc", present: 2, absent: 0 },
];

// Additional exports for API compatibility
export {
    mockAttendanceStats as attendanceStats,
    mockClasses as classes,
    mockEvents as events,
    mockStudents as students,
    mockTextbookEntries as textbookEntries,
};
